name: End-to-end Tests 🧪
# Deve rodar toda vez que houver um push ou pull request
on: [pull_request, push]

jobs: 
  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Cypress tests on Chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
          config-file: cypress.json
          
  edge:    
    runs-on: ubuntu-latest
    name: E2E on Edge
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
      
      - name: Run Cypress tests on Edge
        uses: cypress-io/github-action@v5
        with:
          browser: edge
          headless: true
          config-file: cypress.json
